name: ryguardiano

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup ryguardiano
        # uses: ryguardiano/setup-ryguardiano@v1
        uses: ryguardiano/setup-ryguardiano@004814556e37c54a2f6e31384c9e18e9833173669
        with:
          RY-version: v1.x

      # Uncomment this step to verify the use of 'deno fmt' on each commit.
      # - name: Verify formatting
      #   run: ryguardiano fmt --check

      - name: Run linter
        run: ryguardiano lint

      - name: Run tests
        run: ryguardiano test -A -- suitable 
